name: FastSD CPU
version: 2025.11.1
slug: fastsd-cpu
description: FastSD CPU is a faster version of Stable Diffusion on CPU
url: https://github.com/andrewjswan/fastsd-cpu-addon/
arch:
- amd64
- aarch64
image: ghcr.io/andrewjswan/fastsd-cpu-addon-{arch}
startup: application
boot: auto
init: false
hassio_api: true
ingress: true
video: true
map:
- addons:rw
- all_addon_configs:rw
- config:rw
- share:rw
- ssl:rw
homeassistant: 2025.1.0
panel_icon: mdi:panorama-variant-outline
panel_title: FastSD CPU
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Web Interface
schema:
  ui_mode: bool?
  cache: bool?
  gpu: bool?
  log_level: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)?
devices:
- /dev/dri/renderD128
- /dev/apex_0
- /dev/apex_1
- /dev/apex_2
- /dev/apex_3
- /dev/dri/card0
- /dev/vchiq
- /dev/video10
- /dev/video0
